def book_actions_menu():
    print("1. Borrow Book")
    print("2. Return Book")
    print("3. Reserve Book")
    print("4. Cancel Reservation")
    print("5. List Borrowed Books")
    print("6. List Reserved Books")
    print("7. List All Books")
    print("8. Exit")
    return int(input("Select an action: "))
